FROM jupyter/pyspark-notebook:spark-3.4.1
USER root
RUN apt-get update && apt-get install -y wget && apt-get clean && rm -rf /var/lib/apt/lists/*
RUN wget -P /usr/local/spark/jars https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.4/hadoop-aws-3.3.4.jar
RUN wget -P /usr/local/spark/jars https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.12.262/aws-java-sdk-bundle-1.12.262.jar
RUN pip install numpy==1.26.4 trino==0.329.0 opensearch-py==2.4.0 minio==7.2.8 aiohttp==3.9.5
USER jovyan